//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_maeveSpriteLayout_H
#define METASPRITE_maeveSpriteLayout_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
extern const metasprite_t* const maeveSprite_layout[2];

#endif
