//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_maeveSprite_H
#define METASPRITE_maeveSprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define maeveSprite_TILE_ORIGIN 0
#define maeveSprite_TILE_W 8
#define maeveSprite_TILE_H 8
#define maeveSprite_WIDTH 24
#define maeveSprite_HEIGHT 24
#define maeveSprite_TILE_COUNT 29
#define maeveSprite_PALETTE_COUNT 1
#define maeveSprite_COLORS_PER_PALETTE 4
#define maeveSprite_TOTAL_COLORS 4
#define maeveSprite_PIVOT_X 8
#define maeveSprite_PIVOT_Y 12
#define maeveSprite_PIVOT_W 16
#define maeveSprite_PIVOT_H 24
extern const metasprite_t* const maeveSprite_metasprites[10];

BANKREF_EXTERN(maeveSprite)

extern const palette_color_t maeveSprite_palettes[4];
extern const uint8_t maeveSprite_tiles[464];

#endif
