//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level0_H
#define METASPRITE_level0_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level0_TILE_ORIGIN 0
#define level0_TILE_W 8
#define level0_TILE_H 8
#define level0_WIDTH 480
#define level0_HEIGHT 288
#define level0_TILE_COUNT 0
#define level0_PALETTE_COUNT 1
#define level0_COLORS_PER_PALETTE 4
#define level0_TOTAL_COLORS 4
#define level0_MAP_ATTRIBUTES 0
extern const unsigned char level0_map[2160];
#define level0_map_attributes level0_map

BANKREF_EXTERN(level0)


#endif
