//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 16
#define tileset_WIDTH 16
#define tileset_HEIGHT 144
#define tileset_TILE_COUNT 34
#define tileset_PALETTE_COUNT 1
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 4

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[4];
extern const uint8_t tileset_tiles[544];

#endif
